### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by marvinhagemeister** [1000ch/simplehttp2server#2]
I was sent here by https://github.com/GoogleChrome/simplehttp2server/issues/27#issuecomment-303057430 . Whenever I install simplehttp2server, I get an installation error:

OS: MacOS Sierra

```bash
$ npm i simplehttp2server
> simplehttp2server@1.0.0 postinstall /Users/marvinhagemeister/dev/http2server/node_modules/simplehttp2server
> node lib/install.js

  ⚠ The `/Users/marvinhagemeister/dev/http2server/node_modules/simplehttp2server/vendor/simplehttp2server` binary doesn't seem to work correctly
  ⚠ simplehttp2server pre-build test failed
  ℹ compiling from source
  ✖ Error: mkdir -p /Users/marvinhagemeister/dev/http2server/node_modules/simplehttp2server/vendor && sh crosscompile.sh && mv ./0f3bf125-3c46-428e-94d8-d7546e50273f_darwin_amd64 /Users/marvinhagemeister/dev/http2server/node_modules/simplehttp2server/vendor/simplehttp2server
Command failed: sh crosscompile.sh && mv ./0f3bf125-3c46-428e-94d8-d7546e50273f_darwin_amd64 /Users/marvinhagemeister/dev/http2server/node_modules/simplehttp2server/vendor/simplehttp2server
simplehttp2server.go:24:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/NYTimes/gziphandler (from $GOROOT)
	/Users/marvinhagemeister/go/src/github.com/NYTimes/gziphandler (from $GOPATH)
simplehttp2server.go:24:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/NYTimes/gziphandler (from $GOROOT)
	/Users/marvinhagemeister/go/src/github.com/NYTimes/gziphandler (from $GOPATH)
simplehttp2server.go:24:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/NYTimes/gziphandler (from $GOROOT)
	/Users/marvinhagemeister/go/src/github.com/NYTimes/gziphandler (from $GOPATH)
simplehttp2server.go:24:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/NYTimes/gziphandler (from $GOROOT)
	/Users/marvinhagemeister/go/src/github.com/NYTimes/gziphandler (from $GOPATH)
simplehttp2server.go:24:2: cannot find package "github.com/NYTimes/gziphandler" in any of:
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/NYTimes/gziphandler (from $GOROOT)
	/Users/marvinhagemeister/go/src/github.com/NYTimes/gziphandler (from $GOPATH)

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
http2server@1.0.0 /Users/marvinhagemeister/dev/http2server
```

**Edit:** Seems like this is the same on which leads to the build failures on travis.

**Comment by kahlil** [comment]
Same problem for me.

**Comment by marvinhagemeister** [comment]
@kahlil Nah, telling user to install go is a poor solution, in my opinion. Most node devs don't have go installed, so every new user will run into this error. The proposal in #3 (distributing binaries, instead of go source) is a lot better.

**Comment by kahlil** [comment]
yes of course its better I was just mentioning it as a workaround. 
I wish the PR got merged already... the whole thing fails for me even with Go installed.

**Comment by 1000ch** [comment]
@marvinhagemeister @kahlil Would you try `v2.0.0`?

**Comment by marvinhagemeister** [comment]
@1000ch `v2.0.0` works perfect. Thanks for figuring this one out @surma and @1000ch . You're awesome 👍
