### ISSUE TITLE
Issues installing with `sudo npm install --global simplehttp2server` on osx

### ISSUE THREAD

**Issue by Hillsie** [1000ch/simplehttp2server#6]
Not sure why I am having an issue installing simplehttp2server. hope you can help. It's being referenced in @preact-cli   and it keeps failing at the simplehttp2server install. So I thought I would try out installing only this package. Turns out it fails.

**npm version:**  5.6.0
**node version:** v9.3.0
**Command:**  `sudo npm install --global simplehttp2server`

I used verbose, I'll spare you the success info

```
pm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

...<edited>

npm verb correctMkdir /Users/MacUserName/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/MacUserName/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
npm info lifecycle simplehttp2server@2.0.0~preuninstall: simplehttp2server@2.0.0
npm info lifecycle simplehttp2server@2.0.0~uninstall: simplehttp2server@2.0.0
npm verb unbuild rmStuff simplehttp2server@2.0.0 from /usr/local/lib/node_modules
npm info lifecycle simplehttp2server@2.0.0~postuninstall: simplehttp2server@2.0.0
npm info lifecycle simplehttp2server@2.0.0~preinstall: simplehttp2server@2.0.0
npm info linkStuff simplehttp2server@2.0.0
npm verb linkBins simplehttp2server@2.0.0
npm verb linkBins [ { simplehttp2server: 'cli.js' }, '/usr/local/bin', true ]
npm verb linkMans simplehttp2server@2.0.0
/usr/local/bin/simplehttp2server -> /usr/local/lib/node_modules/simplehttp2server/cli.js
npm info lifecycle simplehttp2server@2.0.0~install: simplehttp2server@2.0.0
npm info lifecycle simplehttp2server@2.0.0~postinstall: simplehttp2server@2.0.0

> simplehttp2server@2.0.0 postinstall /usr/local/lib/node_modules/simplehttp2server
> node lib/install.js

/usr/local/lib/node_modules/simplehttp2server/node_modules/onetime/index.js:15
				throw new Error(fnName + ' can only be called once.');
				^

Error: callback() can only be called once.
    at onetime (/usr/local/lib/node_modules/simplehttp2server/node_modules/onetime/index.js:15:11)
    at /usr/local/lib/node_modules/simplehttp2server/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/simplehttp2server/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:164:20)
    at finishMaybe (/usr/local/lib/node_modules/simplehttp2server/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at endWritable (/usr/local/lib/node_modules/simplehttp2server/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/simplehttp2server/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/simplehttp2server/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:254:19)
    at DuplexWrapper.emit (events.js:164:20)
    
...... <edited>

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simplehttp2server@2.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the simplehttp2server@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]


```

**Comment by Hillsie** [comment]
Might be related to the 5.x updates. Looks like certain permission changes have happened where it saves files. I followed this. https://docs.npmjs.com/getting-started/fixing-npm-permissions which appears to have resolved it.
